//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MovieReviewModel", "fk_reviews_movies", "movies", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MovieReviewModel.Movie), "reviews", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MovieReviewModel.Review))]

// Original file name:
// Generation date: 8/18/2008 12:39:45 AM
namespace MovieReviewModel
{
    
    /// <summary>
    /// There are no comments for MovieRepository in the schema.
    /// </summary>
    public partial class MovieRepository : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new MovieRepository object using the connection string found in the 'MovieRepository' section of the application configuration file.
        /// </summary>
        public MovieRepository() : 
                base("name=MovieRepository", "MovieRepository")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MovieRepository object.
        /// </summary>
        public MovieRepository(string connectionString) : 
                base(connectionString, "MovieRepository")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MovieRepository object.
        /// </summary>
        public MovieRepository(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "MovieRepository")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Movies in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Movie> Movies
        {
            get
            {
                if ((this._Movies == null))
                {
                    this._Movies = base.CreateQuery<Movie>("[Movies]");
                }
                return this._Movies;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Movie> _Movies;
        /// <summary>
        /// There are no comments for Reviews in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Review> Reviews
        {
            get
            {
                if ((this._Reviews == null))
                {
                    this._Reviews = base.CreateQuery<Review>("[Reviews]");
                }
                return this._Reviews;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Review> _Reviews;
        /// <summary>
        /// There are no comments for Movies in the schema.
        /// </summary>
        public void AddToMovies(Movie movie)
        {
            base.AddObject("Movies", movie);
        }
        /// <summary>
        /// There are no comments for Reviews in the schema.
        /// </summary>
        public void AddToReviews(Review review)
        {
            base.AddObject("Reviews", review);
        }
    }
    /// <summary>
    /// There are no comments for MovieReviewModel.Movie in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MovieID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MovieReviewModel", Name="Movie")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Movie : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Movie object.
        /// </summary>
        /// <param name="movieID">Initial value of MovieID.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="releaseDate">Initial value of ReleaseDate.</param>
        public static Movie CreateMovie(int movieID, string title, global::System.DateTime releaseDate)
        {
            Movie movie = new Movie();
            movie.MovieID = movieID;
            movie.Title = title;
            movie.ReleaseDate = releaseDate;
            return movie;
        }
        /// <summary>
        /// There are no comments for Property MovieID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int MovieID
        {
            get
            {
                return this._MovieID;
            }
            set
            {
                this.OnMovieIDChanging(value);
                this.ReportPropertyChanging("MovieID");
                this._MovieID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("MovieID");
                this.OnMovieIDChanged();
            }
        }
        private int _MovieID;
        partial void OnMovieIDChanging(int value);
        partial void OnMovieIDChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property ReleaseDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ReleaseDate
        {
            get
            {
                return this._ReleaseDate;
            }
            set
            {
                this.OnReleaseDateChanging(value);
                this.ReportPropertyChanging("ReleaseDate");
                this._ReleaseDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ReleaseDate");
                this.OnReleaseDateChanged();
            }
        }
        private global::System.DateTime _ReleaseDate;
        partial void OnReleaseDateChanging(global::System.DateTime value);
        partial void OnReleaseDateChanged();
        /// <summary>
        /// There are no comments for Reviews in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MovieReviewModel", "fk_reviews_movies", "reviews")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Review> Reviews
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Review>("MovieReviewModel.fk_reviews_movies", "reviews");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Review>("MovieReviewModel.fk_reviews_movies", "reviews", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MovieReviewModel.Review in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ReviewID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MovieReviewModel", Name="Review")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Review : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Review object.
        /// </summary>
        /// <param name="reviewID">Initial value of ReviewID.</param>
        /// <param name="summary">Initial value of Summary.</param>
        /// <param name="rating">Initial value of Rating.</param>
        /// <param name="body">Initial value of Body.</param>
        public static Review CreateReview(int reviewID, string summary, int rating, string body)
        {
            Review review = new Review();
            review.ReviewID = reviewID;
            review.Summary = summary;
            review.Rating = rating;
            review.Body = body;
            return review;
        }
        /// <summary>
        /// There are no comments for Property ReviewID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ReviewID
        {
            get
            {
                return this._ReviewID;
            }
            set
            {
                this.OnReviewIDChanging(value);
                this.ReportPropertyChanging("ReviewID");
                this._ReviewID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ReviewID");
                this.OnReviewIDChanged();
            }
        }
        private int _ReviewID;
        partial void OnReviewIDChanging(int value);
        partial void OnReviewIDChanged();
        /// <summary>
        /// There are no comments for Property Summary in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary
        {
            get
            {
                return this._Summary;
            }
            set
            {
                this.OnSummaryChanging(value);
                this.ReportPropertyChanging("Summary");
                this._Summary = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Summary");
                this.OnSummaryChanged();
            }
        }
        private string _Summary;
        partial void OnSummaryChanging(string value);
        partial void OnSummaryChanged();
        /// <summary>
        /// There are no comments for Property Rating in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating
        {
            get
            {
                return this._Rating;
            }
            set
            {
                this.OnRatingChanging(value);
                this.ReportPropertyChanging("Rating");
                this._Rating = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Rating");
                this.OnRatingChanged();
            }
        }
        private int _Rating;
        partial void OnRatingChanging(int value);
        partial void OnRatingChanged();
        /// <summary>
        /// There are no comments for Property Body in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Body
        {
            get
            {
                return this._Body;
            }
            set
            {
                this.OnBodyChanging(value);
                this.ReportPropertyChanging("Body");
                this._Body = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Body");
                this.OnBodyChanged();
            }
        }
        private string _Body;
        partial void OnBodyChanging(string value);
        partial void OnBodyChanged();
        /// <summary>
        /// There are no comments for Property Reviewer in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Reviewer
        {
            get
            {
                return this._Reviewer;
            }
            set
            {
                this.OnReviewerChanging(value);
                this.ReportPropertyChanging("Reviewer");
                this._Reviewer = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Reviewer");
                this.OnReviewerChanged();
            }
        }
        private string _Reviewer;
        partial void OnReviewerChanging(string value);
        partial void OnReviewerChanged();
        /// <summary>
        /// There are no comments for Movie in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MovieReviewModel", "fk_reviews_movies", "movies")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Movie Movie
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Movie>("MovieReviewModel.fk_reviews_movies", "movies").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Movie>("MovieReviewModel.fk_reviews_movies", "movies").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Movie in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Movie> MovieReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Movie>("MovieReviewModel.fk_reviews_movies", "movies");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Movie>("MovieReviewModel.fk_reviews_movies", "movies", value);
                }
            }
        }
    }
}
