IF NOT EXISTS(SELECT name FROM master.dbo.syslogins 
        WHERE name = 'NT AUTHORITY\NETWORK SERVICE')
BEGIN
    CREATE LOGIN [NT AUTHORITY\NETWORK SERVICE] FROM WINDOWS 
             WITH DEFAULT_DATABASE=[moviereviews]
    
    CREATE USER [NT AUTHORITY\NETWORK SERVICE] 
            FOR LOGIN [NT AUTHORITY\NETWORK SERVICE] 
            WITH DEFAULT_SCHEMA=[dbo]
END
GO
