//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ClassManager
{
    public partial class Address
    {
        #region Primitive Properties
    
        public string Street
        {
            get;
            set;
        }
    
        public string City
        {
            get;
            set;
        }
    
        public string State
        {
            get;
            set;
        }

        #endregion
    }
}
