//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace ClassManager
{
    public partial class ClassDB : ObjectContext
    {
        public const string ConnectionString = "name=ClassDB";
        public const string ContainerName = "ClassDB";
    
        #region Constructors
    
        public ClassDB()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ClassDB(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ClassDB(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Class> Classes
        {
            get { return _classes  ?? (_classes = CreateObjectSet<Class>("Classes")); }
        }
        private ObjectSet<Class> _classes;
    
        public ObjectSet<Student> Students
        {
            get { return _students  ?? (_students = CreateObjectSet<Student>("Students")); }
        }
        private ObjectSet<Student> _students;

        #endregion
    }
}
