//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ClassManager
{
    public partial class Class
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Student> Students
        {
            get
            {
                if (_students == null)
                {
                    var newCollection = new FixupCollection<Student>();
                    newCollection.CollectionChanged += FixupStudents;
                    _students = newCollection;
                }
                return _students;
            }
            set
            {
                if (!ReferenceEquals(_students, value))
                {
                    var previousValue = _students as FixupCollection<Student>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupStudents;
                    }
                    _students = value;
                    var newValue = value as FixupCollection<Student>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupStudents;
                    }
                }
            }
        }
        private ICollection<Student> _students;

        #endregion
        #region Association Fixup
    
        private void FixupStudents(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Student item in e.NewItems)
                {
                    if (!item.Classes.Contains(this))
                    {
                        item.Classes.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Student item in e.OldItems)
                {
                    if (item.Classes.Contains(this))
                    {
                        item.Classes.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
