//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ClassManager
{
    public partial class Student
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }

        #endregion
        #region Complex Properties
    
        public virtual Address HomeAddress
        {
            get { return _homeAddress; }
            set { _homeAddress = value; }
        }
        private Address _homeAddress = new Address();

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Class> Classes
        {
            get
            {
                if (_classes == null)
                {
                    var newCollection = new FixupCollection<Class>();
                    newCollection.CollectionChanged += FixupClasses;
                    _classes = newCollection;
                }
                return _classes;
            }
            set
            {
                if (!ReferenceEquals(_classes, value))
                {
                    var previousValue = _classes as FixupCollection<Class>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupClasses;
                    }
                    _classes = value;
                    var newValue = value as FixupCollection<Class>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupClasses;
                    }
                }
            }
        }
        private ICollection<Class> _classes;

        #endregion
        #region Association Fixup
    
        private void FixupClasses(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Class item in e.NewItems)
                {
                    if (!item.Students.Contains(this))
                    {
                        item.Students.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Class item in e.OldItems)
                {
                    if (item.Students.Contains(this))
                    {
                        item.Students.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
